### ISSUE TITLE
6.02.3 - afima - Maxime

### ISSUE THREAD

**Issue by apossylkine** [apossylkine/easygrind#1]

**Comment by apossylkine** [comment]
[bugreport.txt](https://github.com/apossylkine/easygrind/files/2483268/bugreport.txt)
![screenshot](https://user-images.githubusercontent.com/44201372/47020078-db37e200-d158-11e8-8ab2-ef28069df1cb.png)

**Comment by mferrari-smp** [comment]
OK v.6.02.6 et v.6.03
