### ISSUE TITLE
[Fraise Up-Down] Usine 2 fois chaque opération

### ISSUE THREAD

**Issue by dleguen** [apossylkine/easygrind#110]
**Version easygrind**
6.03+

**Client**
ASP

**Ce que j'ai vu**
Christophe a changé 2 paramètres et l'usiange est passé de 25 à 50 minutes.

**Comment reproduire**
[9260.zip](https://github.com/apossylkine/easygrind/files/3148401/9260.zip)

**Comment by dleguen** [comment]
![image](https://user-images.githubusercontent.com/23721723/57236549-9f496900-7025-11e9-9d7c-cf78d8879810.png)

**Comment by cfayolle-smp** [comment]
L'outil original a été envoyé par Tools, outil ok. Le second avec l'appellation "brise copeau" est une copie du 1er sur lequel j'ai modifié la description et ajouté des travaux. Conséquence: les travaux de goujures péri sont répétés une 2ème fois, on le voit dans l'iso hors esim et la goujure péri down est répétée avec d'autres travaux intercalés.
[up downø8-2  rtr-brise copeau.zip](https://github.com/apossylkine/easygrind/files/3151721/up.downo8-2.rtr-brise.copeau.zip)
[up downø8-2  rtr.zip](https://github.com/apossylkine/easygrind/files/3151727/up.downo8-2.rtr.zip)

**Comment by mferrari-smp** [comment]
Ok commit #980 . Pour info, un outil "hélice croisées" se comporte comme un outil "toutes dents identiques" , et non pas comme un outil multi-dents". C'est l'action de modifier la description de l'outil qui altère la liste des travaux. IL faut aller dans l'écran de choix des travaux, cliquer sur [Supprimer Tout], valider, puis revenir dans l'écran pour rechoisir à nouveau les tavaux.
