### ISSUE TITLE
[eSim] Les fenêtres de code ISO n'ont pas la bonne taille dans l'onglet ISO

### ISSUE THREAD

**Issue by apossylkine** [apossylkine/easygrind#115]
**Version easygrind**
6.04

**Client**
SMP

**Ce que j'ai vu**
Les fenêtres de code ISO n'ont pas la bonne taille dans l'onglet ISO

**Ce que je m'attendais à voir**
Il faudrait que la fenetre de code prenne toute la place du panel ISO à l'ouverture

**Comment reproduire**
Etapes pour reproduire le bug.

**Screenshots**
Si utile, n'oubliez pas de joindre des captures d'écran.

**Informations complémentaires**
Autres informations/suggestions.

**Comment by mferrari-smp** [comment]
OK v.6.05 par DLG
