### ISSUE TITLE
[eSim] La partie non coupante de certaines meules n'est pas bonne

### ISSUE THREAD

**Issue by apossylkine** [apossylkine/easygrind#119]
**Version easygrind**
6.03+

**Client**
SMP

**Ce que j'ai vu**
Sur une meule chez MF, la partie coupante part en biai au lieu d'être horizontale.

**Ce que je m'attendais à voir**
Les points non coupants devraient être bons (éventuellement dupliquer les points dans eSim)

**Comment reproduire**
Voir MF pour type de meule

**Screenshots**
Si utile, n'oubliez pas de joindre des captures d'écran.

**Informations complémentaires**
Autres informations/suggestions.

**Comment by mferrari-smp** [comment]
soldé suite à l'évolution des corps de meule dessinés avec un retrait
