### ISSUE TITLE
Easygrind : plongées sur plaquette

### ISSUE THREAD

**Issue by cfayolle-smp** [apossylkine/easygrind#123]
**Problème**
Dans l'écran des plongées, le client demande la possibilité de zoomer ou dé zoomer car il n'a pas la visualisation complète des plongées. Cela dépend de la taille du profil (voir fichier joint).

**Solution envisagée**
Description de comment résoudre le problème

**Client**
A2C
[test ebauche par etage pour plaquette hockey.zip](https://github.com/apossylkine/easygrind/files/3216006/test.ebauche.par.etage.pour.plaquette.hockey.zip)

**Documents et remarques supplémentaires**

**Comment by mferrari-smp** [comment]
ok 6.05
