### ISSUE TITLE
Fraise 2T toutes dents différente

### ISSUE THREAD

**Issue by msaou** [apossylkine/easygrind#128]
**Version easygrind**
6.04

**Client**
Euromac

**Ce que j'ai vu**
Erreur a la création d'un outil en toutes dents différentes

**Ce que je m'attendais à voir**

**Comment reproduire**
Créer une fraise en toutes dents différentes et choisir un travail 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/44203183/59022005-41d75080-884d-11e9-99d3-c4e155ac6653.PNG)
[bugreport.txt](https://github.com/apossylkine/easygrind/files/3260910/bugreport.txt)

**Informations complémentaires**
Autres informations/suggestions.

**Comment by mferrari-smp** [comment]
OK v.6.04.1 et v.6.05
commit 1009
