### ISSUE TITLE
Alsa Meca n'a pas une bonne version

### ISSUE THREAD

**Issue by apossylkine** [apossylkine/easygrind#134]
**Version easygrind**
6.03.0 et eSim 1.41

**Client**
Alsa Meca

**Ce que j'ai vu**
La 1.41 n'est pas officiellement compatible avec la 6.03 mais la 6.04.

**Ce que je m'attendais à voir**
Alsa Meca devrait être passé sur la 6.04 pour être "propre"

**Comment reproduire**
Toutes les machines chez eux ont la 6.03 indice 0 et eSim de la 6.04 indice 1.
Ca marche, mais c'est inquietant

**Screenshots**
Si utile, n'oubliez pas de joindre des captures d'écran.

**Informations complémentaires**
Autres informations/suggestions.

**Comment by mferrari-smp** [comment]
OK fait par MS
