### ISSUE TITLE
Fraise bout rayonnée de forme géométrique

### ISSUE THREAD

**Issue by cfayolle-smp** [apossylkine/easygrind#139]
**Version easygrind**
peu importe

**Client**
PSA Cergy

**Ce que j'ai vu**
Avec la description "fraise bout rayonnée de forme géométrique, 2 goujures en bout" il manque le travail "goujure en bout 2". Si la fraise bout rayonnée n'est plus déclarée de forme géométrique alors le travail "goujure bout 2" est proposé.

**Ce que je m'attendais à voir**

**Comment reproduire**
Etapes pour reproduire le bug.

**Screenshots**
Si utile, n'oubliez pas de joindre des captures d'écran.

**Informations complémentaires**
Autres informations/suggestions.

**Comment by mferrari-smp** [comment]
Ok v.6.05 commit 1062
