### ISSUE TITLE
[Fraise à fraisurer] travail de raccourcissement

### ISSUE THREAD

**Issue by cfayolle-smp** [apossylkine/easygrind#141]
**Version easygrind**
toutes

**Client**
SMP

**Ce que j'ai vu**
En sélectionnant une meule boisseau (meule standard pour ce travail) la case devient rouge

**Ce que je m'attendais à voir**
Description du comportement attendu.

**Comment reproduire**
Etapes pour reproduire le bug.

**Screenshots**
Si utile, n'oubliez pas de joindre des captures d'écran.

**Informations complémentaires**
Autres informations/suggestions.

**Comment by mferrari-smp** [comment]
OK v.6.05
