### ISSUE TITLE
[FRAISE] Mouvement du B avant chg meule 

### ISSUE THREAD

**Issue by msaou** [apossylkine/easygrind#143]
**Version easygrind**
3.04.4

**Client**
EUROMAC

**Ce que j'ai vu**
Dans l'outil on a deux travaux une goujure en péri + chanfrein avec un changement  de meule entre les deux.
Après la fin de la goujure péri l'axe B prend la position du chanfrein (B44) avant de revenir a zéro et changer la meule.

**Ce que je m'attendais à voir**
Description du comportement attendu.

**Comment reproduire**
Simuler l'outil

**Screenshots**
[Alésoir.zip](https://github.com/apossylkine/easygrind/files/3430936/Alesoir.zip)

**Informations complémentaires**
Dans l' iso on appel (N6032 X354.198 Z68.998 B44) avant changement meule ligne a supprimer

**Comment by dleguen** [comment]
OK v.6.05 commit 1094

**Comment by msaou** [comment]
Sur mon poste avec la 6.04.8 on a toujours le problème
![2019-08-02_08h48_17](https://user-images.githubusercontent.com/44203183/62350681-c370f500-b503-11e9-9b12-bf6cb4a18926.png)
