### ISSUE TITLE
[eSim] 1.64 Probleme de brut extrudé

### ISSUE THREAD

**Issue by mferrari-smp** [apossylkine/easygrind#146]
**Version easygrind**
6.05 du 7/8/2019 & eSim 1.64 

**Client**
BH (j'ai remis eSim 1.59 en attendant)

**Ce que j'ai vu**
Sur la broche plate, plusieurs soucis : 
- le brut n'est pas dans le bon sens (position X ok)
- les meules ne coupent pas

**Screenshots**
![image 001](https://user-images.githubusercontent.com/44203060/62607299-21d01600-b8fe-11e9-9e48-9284abf36add.PNG)

**Fichier Snap**
[pb brut extrude - pas d enlevement de matiere.zip](https://github.com/apossylkine/easygrind/files/3476015/pb.brut.extrude.-.pas.d.enlevement.de.matiere.zip)

**Comment by apossylkine** [comment]
OK #1102
