### ISSUE TITLE
6.03 fraise crest cut n'usine que les 3 premières dents sur 6

### ISSUE THREAD

**Issue by dleguen** [apossylkine/easygrind#15]
N° de bloc inexistant N2400

**Comment by dleguen** [comment]
[eurocopter 5000.zip](https://github.com/apossylkine/easygrind/files/2533433/eurocopter.5000.zip)

**Comment by dleguen** [comment]
Lié à une modification des n° de blocs en multipasse par décalages

**Comment by mferrari-smp** [comment]
Ok 6.02.6 & 6.03
