### ISSUE TITLE
[eSim] Comportement curieux des collisions a enqueter

### ISSUE THREAD

**Issue by apossylkine** [apossylkine/easygrind#164]
**Version easygrind**
6.05

**Client**
A2C

**Ce que j'ai vu**
SIgnale un truc bizarre sur un outil

**Ce que je m'attendais à voir**
Description du comportement attendu.

**Comment reproduire**
Un snap est fourni, à voir avec Christian
[C10752-Z000360326 MR 01-02-19 PLAN 2258 TEST.zip](https://github.com/apossylkine/easygrind/files/3701885/C10752-Z000360326.MR.01-02-19.PLAN.2258.TEST.zip)

**Screenshots**
Si utile, n'oubliez pas de joindre des captures d'écran.

**Informations complémentaires**
Autres informations/suggestions.

**Comment by apossylkine** [comment]
La meule était invalide, eSim ne signale pas le souci mais ne dessine pas la bonne meule à l'écran.

**Comment by mferrari-smp** [comment]
Vu avec le client ce jour : il avait une meule torique 1E1 avec un angle = 90 qui donnait un dessin de meule trop bizarre. En simulation, la meule ne se voyait pas, ne faisait pas d'enlèvement de matière.
SUGGESTION : peut-on renvoyer un message d'erreur quand la meule simulée ne "fonctionne" pas ?
