### ISSUE TITLE
[Fraise 3 taille] Soucis urgent confusion Gr1/Gr2

### ISSUE THREAD

**Issue by apossylkine** [apossylkine/easygrind#168]
**Version easygrind**
6.03+

**Client**
ASP

**Ce que j'ai vu**
Pas bien compris le souci présenté par Christophe d'ASP. Il s'agit de prendre le mauvais parametre entre Gr1 et Gr2.
Le paramètre "Incline Meule Péri Gr2" ne fonctionne pas (prend la valeur du groupe 1)

**Fichier SNAP**
[ASP_3tailles_80z20.zip](https://github.com/apossylkine/easygrind/files/3734540/ASP_3tailles_80z20.zip)

**Comment by mferrari-smp** [comment]
modif faite dans v.6.05 commit #1161

**Comment by mferrari-smp** [comment]
OK 6.05 commit #1161
