### ISSUE TITLE
[BROCHES] Rayon sur broche plate enfonce la broche

### ISSUE THREAD

**Issue by dleguen** [apossylkine/easygrind#18]
**Version easygind**
6.02 fonctionne pas, 5.15.3 fonctionne

**Client**
BH

**Ce que j'ai vu**
Usinage du rayon sur broche plate : enfonce l'outil de plusieurs millimetres. Le fait d'ouvrir l'outil avec la 6.02 "corrompt" le fichier qui fait la même chose avec la 5.15

**Comment reproduire**
Snap

**Comment by dleguen** [comment]
[PB BH.zip](https://github.com/apossylkine/easygrind/files/2547510/PB.BH.zip)

**Comment by mferrari-smp** [comment]
Résolu commit #905 v.6.04
