### ISSUE TITLE
[eSIM] : état de surface bizarre

### ISSUE THREAD

**Issue by mferrari-smp** [apossylkine/easygrind#29]
**Version easygrind**
6.02.3 du 28/09/2018, eSimServer 1.39

**Client**
ASP sur CA3 210

**Ce que j'ai vu**
la simulation donne un rendu très bizarre (outil esim 20z4 + copie d'écran)
Piste : cela vient peut-être de la meule ...
![2018-11-14_16h02_06](https://user-images.githubusercontent.com/44203060/48492152-6f18ce80-e829-11e8-93fc-b01959859126.png)
**Fichier outil**
[esim 20z4.zip](https://github.com/apossylkine/easygrind/files/2581347/esim.20z4.zip)

**Comment by apossylkine** [comment]
Probleme dû a la meule : largeur de bande 0.725 passé a 1.0 => RESOLU

![image](https://user-images.githubusercontent.com/44201372/48493315-e18aae00-e82b-11e8-9908-c8455542e196.png)

Penser a ajouter des bornes sur les parametres de meules pour eviter les meules fausses

**Comment by mferrari-smp** [comment]
OK v.6.03 15 nov et 6.02.7 (j'ai triché le dessin de la meule boisseau quand le bandeau n'est pas assez large)
