### ISSUE TITLE
6.01 - Gilles Morley

### ISSUE THREAD

**Issue by apossylkine** [apossylkine/easygrind#3]
Gilles Morley
hélice décalée dépouille curviligne, lignes ICO dupliquées

**Comment by apossylkine** [comment]
A demandé l'installation de la 5.16 (en a marre)

**Comment by mferrari-smp** [comment]
Commit 803. FRAISE MULTI-DENTS :
-Fixed : quand on change la description d'une frais "multi-dents" et "Toutes dents identiques", la liste des travaux "multi-dents" ne se mettait pas à jour
vers une liste de travaux simples. ce bug est apparu dans la 6.01
