### ISSUE TITLE
[eSIM] - Comportement travail usinage incoherent avec les anciennes versions

### ISSUE THREAD

**Issue by apossylkine** [apossylkine/easygrind#30]
**Version easygrind**
6.03

**Ce que j'ai vu**
Sur la version 6.03 le travail 5 ne touche pas le brut, alors que sur la 6.02 il s'effectue correctement

**Ce que je m'attendais à voir**
Le travail 5 devrait operer correctement et usiner le brut comme ceci:

![image](https://user-images.githubusercontent.com/44201372/48493315-e18aae00-e82b-11e8-9908-c8455542e196.png)
**Comment reproduire**
Charger le snap contenu dans esim.20z4 et executer les travaux 4,5 et 6

**Screenshots**
![image](https://user-images.githubusercontent.com/44201372/48494368-0a13a780-e82e-11e8-85df-52f5bcf3add8.png)

**Informations complémentaires**
[esim.20z4.zip](https://github.com/apossylkine/easygrind/files/2581444/esim.20z4.zip)

**Comment by apossylkine** [comment]
[ISO_6.03.txt](https://github.com/apossylkine/easygrind/files/2581579/ISO_6.03.txt)
[ISO_6.02.5.txt](https://github.com/apossylkine/easygrind/files/2581580/ISO_6.02.5.txt)
ISO pour la CN générés par Easygrind

**Comment by mferrari-smp** [comment]
![2018-11-14_17h12_36](https://user-images.githubusercontent.com/44203060/48495592-a048cd00-e830-11e8-84c6-672f25095ade.png)

**Comment by apossylkine** [comment]
`pnl_Simulation.MWSetCollision(true);
pnl_Simulation.MWSetCuttingMode(true);
pnl_Simulation.MWPlay(PLAY_FAST);
//permet de dire qu'a la fin de l execution on a une simulation finie
//et prete a etre utilisee
pnl_Simulation.FMWCommands.sendToThread(TCommandEndSimulation.Create);
pnl_Simulation.MWSetCollision(false);`

Si je commente les deux `pnl_Simulation.MWSetCollision`, plus de soucis. Je continue l'enquête

**Comment by apossylkine** [comment]
OK 6.4 (commit 908) 
![image](https://user-images.githubusercontent.com/44201372/52849034-7396a100-3110-11e9-9ae5-40feb609d839.png)
