### ISSUE TITLE
[FORET] - Etage spiroconique différents depuis la v.6.02 (Alsameca)

### ISSUE THREAD

**Issue by mferrari-smp** [apossylkine/easygrind#34]
**Version easygrind**
6.02

**Client**
ALSAMECA

**Ce que j'ai vu**
trajectoire bizarre et beaucoup  plus lent qu'avant

**Fichier Outil**
[oalqc112 1 seul programme.zip](https://github.com/apossylkine/easygrind/files/2585691/oalqc112.1.seul.programme.zip)

**Comment by mferrari-smp** [comment]
Modification faite dans la v.5.14.10 pour ASP le 04/04/2017, l'explication est la suivante : 
"Travail de dépouille spiroconique : en méthode G, Z, on travaille coté Z-, Lorsque le travail précédent est un travail en bout, l'accostage déglingue l'outil. J'ai décomposé les axes: d'abord Y, puis Z, puis le reste., DLG, non testé!"
![foret_etage_spiro_accostage](https://user-images.githubusercontent.com/44203060/48768346-22197a00-ecb9-11e8-82ed-2b5c4b29fe63.png)

**Comment by dleguen** [comment]
Commit 861 version 6.03
