### ISSUE TITLE
[FRAISE] - erreurs butée Z ou Y, la CN ne bouge plus (Alsameca)

### ISSUE THREAD

**Issue by mferrari-smp** [apossylkine/easygrind#35]
**Version easygrind**
6.02

**Client**
Alsameca

**Ce que j'ai vu**
Fraise 2T : erreurs butée Z ou Y, la CN ne bouge plus , l'arrosage reste actif pendant l'opération de goujure en bout

**Fichier Outil**

[10000 z3.zip](https://github.com/apossylkine/easygrind/files/2585793/10000.z3.zip)

![alasameca_hors course z fraise](https://user-images.githubusercontent.com/44203060/48560160-80c3aa00-e8ed-11e8-9d25-b0ccf850dd0b.jpg)

**Comment by dleguen** [comment]
A valider 6.03 Commit 860
