### ISSUE TITLE
[eSim] - Erreur quand on bascule Rapide/Précis sans jamais avoir simulé

### ISSUE THREAD

**Issue by mferrari-smp** [apossylkine/easygrind#59]
**Version easygrind**
6.03
**Client**
PC_FERRARI

**Ce que j'ai vu**
J'ai changé la précision de la simulation avant de lancer la première simulation.

![2018-11-27_17h38_09](https://user-images.githubusercontent.com/44203060/49096879-d55f1180-f26b-11e8-846a-271e15f341a4.png)

**Suggestion**
J'ai recompilé le programme SANS madExcept, l'erreur affichée semble "moins effrayante" ... à méditer
![2018-11-27_17h40_33](https://user-images.githubusercontent.com/44203060/49096882-d728d500-f26b-11e8-8191-0fafed8d38a8.png)

**Comment by apossylkine** [comment]
OK 6.04 #876
