### ISSUE TITLE
[eSim] - Alésoir 4 dents enchainé avec une rectif simule les 4 dents au même endroit

### ISSUE THREAD

**Issue by mferrari-smp** [apossylkine/easygrind#60]
**Version easygrind**
6.02.7

**Client**
ASP

**Ce que j'ai vu**
Il usine un alésoir à 4 dents. 
S'il déclare le fichier seul "9091", la simule est OK. 
S'il déclare le fichier "9091\~01" pour l'enchainer avec un second fichier "9091~02", cela simule les 4 dents au même endroit.

**Fichiers outils**
[9091.zip](https://github.com/apossylkine/easygrind/files/2633893/9091.zip)

**Comment by apossylkine** [comment]
Le souci provenait du reader ISO. L'outil voulait charger un H140, qui n'était pas chargé correctement (vide). OK 6.04+ commit 957
