### ISSUE TITLE
[eSim] La barre de travaux afffiche moins de travaux qu'en vrai

### ISSUE THREAD

**Issue by dleguen** [apossylkine/easygrind#79]
**Version easygrind**
6.03

**Client**
SMP

**Ce que j'ai vu**
![image](https://user-images.githubusercontent.com/23721723/51983649-89159500-2499-11e9-9d48-f9021bc1c9ff.png)

**Comment reproduire**
Lancer la simulation

**Informations complémentaires**
[fr 3t z26 r4 02.zip](https://github.com/apossylkine/easygrind/files/2812664/fr.3t.z26.r4.02.zip)

**Comment by apossylkine** [comment]
L'avance de la goujure etait a 0, donc en vitesse minimale, ce qui prenait des jours, manquant ainsi les autres travaux de la timeline.
Pas bug.
