### ISSUE TITLE
[eSim] Ne simuler qu'une dente lorsque NCSimul n'a jamais été installé

### ISSUE THREAD

**Issue by dleguen** [apossylkine/easygrind#81]
**Version easygrind**
6.03+

**Client**
Tous

**Ce que j'ai vu**
Lorsque NCSimul n'a jamais été installé sur le poste, l'option "ne simuler qu'une seule dent" est grisée

**Comment by mferrari-smp** [comment]
a tester v.6.04

**Comment by mferrari-smp** [comment]
6.04 *FRAISE MULTI-DENTS : 
OK commit #982 v.6.04
