### ISSUE TITLE
[Bug] Erreur IRealTimeStylus

### ISSUE THREAD

**Issue by dleguen** [apossylkine/easygrind#84]
**Version easygrind**
6.3

**Client**
BH

**Ce que j'ai vu**
Plusieurs fois par jour, le message suivant apparait
![image](https://user-images.githubusercontent.com/23721723/53076634-66066000-34f0-11e9-88c6-c67d7f35d13a.png)
Ok -> ca continue à fonctionner

**Comment reproduire**
C'est fréquent, mais pas de pattern pour le moment

**Informations complémentaires**
sur les CA7 103, 115 et 123

**Comment by dleguen** [comment]
Commit 909 et 910
6.03.4 et 6.04

**Comment by stalker474** [comment]
T'as trouvé le souci?

**Comment by dleguen** [comment]
Je suis pas sur, mais j’explore une piste qui va vers la gestion du tactile. Version envoyée à CF aujourd’hui, il teste et me redit

Cordialement,
Best regards,
[cid:image001.png@01D4C920.F1458AB0]
                     Damien Le Guen
                     Ingénieur développement EasyGrind
                     EasyGrind Software Engineer
                Tel : +33 (0)4 72 15 48 01
                    dleguen@smp.fr<mailto:dleguen@smp.fr>
                    122 Av Pasteur - ZAC du bois Chevrier
                    F-69740 Toussieu
                    www.smp.fr<http://www.smp.fr/>
--- Afin de contribuer au respect de l'environnement, merci de n'imprimer cet email que si nécessaire.---
Retrouvez nos vidéos sur : https://www.youtube.com/user/SMPtechnik


De : stalker474 <notifications@github.com>
Envoyé : mercredi 20 février 2019 13:32
À : apossylkine/easygrind <easygrind@noreply.github.com>
Cc : Damien Le Guen <dleguen@smp.fr>; Assign <assign@noreply.github.com>
Objet : Re: [apossylkine/easygrind] [Bug] Erreur IRealTimeStylus (#84)


T'as trouvé le souci?

**Comment by apossylkine** [comment]
Confirmé par christian
