### ISSUE TITLE
[Fraise] Travaux à l'edition pas dans le bon ordre 

### ISSUE THREAD

**Issue by dleguen** [apossylkine/easygrind#86]
**Version easygrind**
6.03

**Client**
ASP

**Ce que j'ai vu**
La liste des travaux de la simulation ne correspond pas à la liste de travaux. L'ordre n'est pas respecté. Même problème dans NCSimul : le pb est donc dans l'iso 

**Ce que je m'attendais à voir**
Travaux dans le bon ordre

**Comment reproduire**
[2CC-D00-023.zip](https://github.com/apossylkine/easygrind/files/2906065/2CC-D00-023.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/23721723/53422289-7e3e1980-39df-11e9-8546-5f4402ad81cb.png)

**Comment by mferrari-smp** [comment]
les travaux étaient mélangés (uniquement pour fraise multi-dents. 
Remarque : ce problème pouavit survenir en manipulalnt la liste des travaux choisis dans l'écran de choix des travaux : changer de place un travail choisi en glisser-deposer, et il s'insérait parfaois au milieu d'un autre travail.
Sucurité supplémantaire : à la lacture d'n outil, on s'assure que les travaux multi-dents sont dans le bon ordre, et complet. On corrige si nécessaire.

Commit #982 v.6.04
