### ISSUE TITLE
[Broches] Collision broche plate pied de sapin

### ISSUE THREAD

**Issue by dleguen** [apossylkine/easygrind#87]
**Version easygrind**
6.03

**Client**
SMOC

**Ce que j'ai vu**
Mange la broche. Vu Sébastien et Frederic

**Comment reproduire**
Outil à récupérer. Déclaré broche debout D avec A180, en Gen et Oppo gen

**Comment by mferrari-smp** [comment]
soldé - les accostages étaient mal configurés
