### ISSUE TITLE
ESIM  collision avec corps de meule

### ISSUE THREAD

**Issue by msaou** [apossylkine/easygrind#96]
**Version easygrind**
V6.04 ANTON V1.51 ESIM

**Client**
SMP

**Ce que j'ai vu**
- on a une collision dans le taillage d'une goujure, avec le corp de la meule 

**Ce que je m'attendais à voir**
- En réalité le corps de la meule est légèrement en retrais par rapport au bandeau de meule. 
- On aura peut être besoin d'un paramètre supplémentaire dans la déclaration de meule. 
**Comment reproduire**
Etapes pour reproduire le bug.
- Programmé une goujure avec une meule cylindrique.
**Screenshots**
![collision corp de meule](https://user-images.githubusercontent.com/44203183/55329830-da3d0780-548f-11e9-81d8-0e632560571c.PNG)

**Informations complémentaires**
Autres informations/suggestions.

**Comment by apossylkine** [comment]
Suite recommandation Moduleworks, voici la modif apportée

options.MaxMoveAngle = 0.75;
//options.MaxMoveLength = 1;

Mail MW 
Thank you for the log file, we analyzed it and the collision seems to be precision related. When the MaxMoveAngle is set  for example to 0.25 there is no such collision. You can set this value in cncsim::mwSimulationOptions
