### ISSUE TITLE
[esim] la simul est fausse

### ISSUE THREAD

**Issue by msaou** [apossylkine/easygrind#97]
**Version easygrind**
6.04 ANTON V1.51

**Client**
SMP

**Ce que j'ai vu**
Le programme fonctionne bien sur la v6.03 v1.41

**Ce que je m'attendais à voir**
Description du comportement attendu.

**Comment reproduire**
simul de l'outil

**Screenshots**

[Taper lok.zip](https://github.com/apossylkine/easygrind/files/3030377/Taper.lok.zip)

**Informations complémentaires**
Autres informations/suggestions.

**Comment by apossylkine** [comment]
Erreur lors du chargement des snaps, possible d'avoir les outils et les meules à l'ancienne?

**Comment by msaou** [comment]
[Taper lok.zip](https://github.com/apossylkine/easygrind/files/3053863/Taper.lok.zip)

**Comment by apossylkine** [comment]
Tu peux resimuler cet outil avec la 6.04 officielle et dire s'il y'a encore un souci?

**Comment by msaou** [comment]
C'est OK sur la V6.04

**Comment by apossylkine** [comment]
Merci, je ferme le problème du coup!
