### ISSUE TITLE
[Alesoirs] Easygrind en Y moins l'infini

### ISSUE THREAD

**Issue by apossylkine** [apossylkine/easygrind#99]
**Version easygrind**
6.04

**Client**
Mustaffa

**Ce que j'ai vu**
Programme Alesoir edite une ligne où le Y doit aller très loin dans les négatifs. La simulation plante.

**Ce que je m'attendais à voir**
Le Y doit être compris entre le min et le max de cet axe

**Comment reproduire**
[AlésoirØ10-z6-ch30.zip](https://github.com/apossylkine/easygrind/files/3053292/AlesoirO10-z6-ch30.zip)

C'est plus simple à voir en ne lançant que le dernier travail.
On peut alors voir ligne 83 :
N10020 G1  X 282.532 **Y-1000000000000000.000** Z 124.170 A-151.8580 B  29.5107 F0.01

**Screenshots**
Si utile, n'oubliez pas de joindre des captures d'écran.

**Informations complémentaires**
Autres informations/suggestions.

**Comment by dleguen** [comment]
Commit 948 
Version 6.04

**Comment by apossylkine** [comment]
Validé 6.04
